---
title: "Thèse Jenny CMF"
author: "Francesco Monti"
date: 
output:
  officedown::rdocx_document: default
  word_document: default
subtitle: Revue des pratiques gingivopériostoplastie
---

```{r libraries, echo = F, include=F}
library(tidyverse)     # The main "tidyverse" packages.
library(conflicted)    # Get a warning/error if several functions with the same name exist.
conflicts_prefer(dplyr::filter)
library(magrittr)      # Operator %>% and additional pipe-friendly functions.
library(pander)
library(Kendall)
library(psych)
library(lmtest)
library(knitr)         # Function `kable()` to convert data frames into tables for reports.
#knitr::opts_knit$set(root.dir='..')

library(kableExtra)        # Enhancing kable() possibilities
library(DT)            # Interactive tables for HTML documents (DataTables).
library(fmckage)
library(janitor)
library(ggthemes)

library(ProjectTemplate)
#setwd("..")
load.project()
library(officer)
library(flextable)
library(officedown)
```

```{r options, echo = F}
# Chunk options
knitr::opts_chunk$set(
  echo       = F,    # Should blocks with program code be shown in knitted documents?
  eval       = TRUE,    # Should program code be evaluated?
  #fig.height = 6,       # Default height for plots.
  #fig.width  = 10,       # Default width for plots.
  fig.align  = "center", # Default alignment for plots in knitted documents.
  warning = F
  #fig.fullwidth = T
)

# Options to format numbers
options(        # For more detais see ?options
  scipen = 8,   # Show at least 8 digits in numbers before converting to exponential notation.
    digits = 2,   # Number of significant digits to print numbers.
    OutDec = ".", # Default decimal separator to print numbers.
    knitr.kable.NA = NA # Replacement for NA values in knitr::kable()
)

# Set ggplot options
theme = theme_clean()+
    theme(  # You can choose a pre-defined theme or customize it further
    text = element_text(color = "black", size = 12),
    axis.title = element_text(face = "bold"),
    title = element_text(face = "bold"))
theme_set(theme)

# Flextable defaults
set_flextable_defaults(
  font.family = "Helvetica",
  font.size = 8,
  #padding = 2,
  border.color = "#CCCCCC",
  line_spacing = 1,
  digits = 2,
  na_str = "",
  float = "float"
  )

```

# Epidemio {.tabset}
## Sexe
```{r sexe}
table_prop(epi$sexe) %>% 
  `colnames<-`(c("Gender","n","%")) %>% 
  flextable()
  # kable(caption = "Gender", col.names = c("Gender","n","%")) %>% 
  # kable_paper() %>% 
  # kable_styling(bootstrap_options = c("striped", "hover"))
```

## Fentes
```{r fentes}
##### Table 1 ------------
rbind(table_prop(epi$complete),
      table_prop(epi$cote)) %>% 
  mutate(var = c("No","Yes","Both","Right","Left","NA"),
         group = c(rep("Complete", 2), rep("Affected side", 4))) %>% 
  relocate(group, .before = dplyr::first(colnames(.))) %>% 
  as_grouped_data(groups = c("group")) %>% 
    flextable() %>% 
  set_header_labels(group = "Feature", var = "", n = "N", prop = "%") %>% 
  bold(j = 1, part = "body") %>%
  bold(part = "header") %>% 
  set_table_properties(width = 1, layout = "autofit")
  # kable(col.names = c("Feature","n","%"), caption = "Cleft characteristics") %>%
  # kable_paper() %>% 
  # pack_rows(start_row = 1,end_row = 2,"Complete") %>% 
  # pack_rows(start_row = 3,end_row = 6,"Affected side") %>% 
  # kable_styling(bootstrap_options = c("striped", "hover"))
```
 
 dfgsdfgsdfsgfdsgdfg

<div style="page-break-after: always;"></div>


```{r fntes}

# Table2 prep -----------
tab = table(epi$complete,epi$cote, deparse.level = 2, useNA = "ifany") %>% 
  data.frame() %>%
  rename(complete = epi.complete, `affected side` = epi.cote, n = Freq) %>% 
  mutate(complete = rep(c("No","Yes"),4),
         "%" = n*100/sum(n),
         `affected side` = case_when(`affected side` == "bilaterale" ~ "Both",
                                     `affected side` == "droite" ~ "Right",
                                     `affected side` == "gauche" ~ "Left"),
         "Gender"=""
         ) %>% 
  `colnames<-`(str_to_title(colnames(.))) %>% adorn_totals() %>% 
    relocate(Gender, .before = "Complete")

tabf = table("gender"= epi$sexe[epi$sexe=="F"], 
             epi$complete[epi$sexe=="F"],
             epi$cote[epi$sexe=="F"], deparse.level = 2, useNA = "ifany") %>% 
  data.frame() %>%
  `colnames<-`(c("gender", "complete", "affected side", "n")) %>% 
  mutate(complete = case_when(complete == 0 ~ "No",
                              complete == 1 ~ "Yes"),
         "%" = n*100/sum(n),
         `affected side` = case_when(`affected side` == "bilaterale" ~ "Both",
                                     `affected side` == "droite" ~ "Right",
                                     `affected side` == "gauche" ~ "Left")
    ) %>% 
    `colnames<-`(str_to_title(colnames(.)))  %>% 
    arrange(desc(N)) %>% adorn_totals

tabm = table("gender"= epi$sexe[epi$sexe=="M"], 
             epi$complete[epi$sexe=="M"],
             epi$cote[epi$sexe=="M"], deparse.level = 2, useNA = "ifany") %>% 
  data.frame() %>%
  `colnames<-`(c("gender", "complete", "affected side", "n")) %>% 
  mutate(complete = case_when(complete == 0 ~ "No",
                              complete == 1 ~ "Yes"),
         "%" = n*100/sum(n),
         `affected side` = case_when(`affected side` == "bilaterale" ~ "Both",
                                     `affected side` == "droite" ~ "Right",
                                     `affected side` == "gauche" ~ "Left")
    ) %>% 
    `colnames<-`(str_to_title(colnames(.)))  %>% 
    arrange(desc(N)) %>% adorn_totals

# Table 2 ------
rbind(tab,tabf,tabm) %>%
  #relocate(Gender, .before = "Complete") %>% 
  as_grouped_data(groups = "Gender") %>%
  flextable() %>% 
  bold(j = 1, part = "body") %>%
  bold(part = "header") %>% 
  set_table_properties(width = 1, layout = "autofit", opts_word = list(`keep_with_next` = T)) %>% 
  line_spacing(space=.2)


 # rbind(tab,tabf,tabm) %>% select(-Gender) %>% 
 #  kable(row.names = F, caption = "Clefts characteristics cross-table") %>%
 #  kable_paper() %>% 
 #  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>% 
 #  add_footnote(c("NA = Not Available")) %>% 
 #  pack_rows("Overall",1,9) %>% 
 #  pack_rows("Females",10,18) %>% 
 #  pack_rows("Males",19,26)
```
