---
title:    "Thèse Jenny CMF"
subtitle: "Revue des pratiques gingivopériostoplastie"
author:   "Francesco Monti"
date:     "2023-07-25 12:26:12" # Automatic date
output:
    bookdown::html_document2: 
        toc:         yes        # Table of contents (toc): yes no
        toc_float:   yes        # yes no
        toc_depth:   3              # 1 2 3 4 5
        highlight : pygments      # default tango kate monochrome espresso pygments...
        highlight_downlit : FALSE      # TRUE to use the downlit package as syntax highlight engine to highlight inline code and R code chunks (including providing hyperlinks to function documentation). The package needs to be installed to use this feature.
        code_folding:    "hide"     # none show hide
        code_download:   yes        # yes no
        fig_caption: yes        # yes no
        fig_width : 7
        fig_height : 5
        fig_retina : 2
        theme:       default        # cerulean journal flatly readable paper sandstone ...
        df_print:    default        # paged kable tibble default
        number_sections: yes        # Automatic numbering of sections: yes no
        anchor_sections : FALSE
        section_divs : TRUE     # Wrap sections in <div> tags, and attach identifiers to the enclosing <div> rather than the header itself.
        dev : "png"                # Graphics device to use for figure output (defaults to png)
        self_contained : TRUE
        extra_dependencies : NULL    # Extra dependencies as a list of the html_dependency class objects typically generated by htmltools:htmlDependency().
        css : NULL     # CSS and/or Sass files to include. Files with an extension of .sass or .scss are compiled to CSS via sass::sass(). Also, if theme is a bslib::bs_theme() object, Sass code may reference the relevant Bootstrap Sass variables, functions, mixins, etc.
        includes : NULL        # Named list of additional content to include within the document (typically created using the includes function)
        keep_md : FALSE        # Keep the markdown file generated by knitting.
        lib_dir : NULL             #    Directory to copy dependent HTML libraries (e.g. jquery, bootstrap, etc.) into. By default this will be the name of the document with _files appended to it.
        md_extensions : NULL       # Markdown extensions to be added or removed from the default definition of R Markdown. See the rmarkdown_format for additional details.
        pandoc_args : NULL      # Additional command line options to pass to pandoc
        template : "default"  
editor_options: 
  chunk_output_type: console
---

```{r libraries, echo = F, include=F}
library(tidyverse)     # The main "tidyverse" packages.
library(conflicted)    # Get a warning/error if several functions with the same name exist.
conflicts_prefer(dplyr::filter)
library(magrittr)      # Operator %>% and additional pipe-friendly functions.
library(pander)
library(forecast)
library(tseries)
library(psych)
library(lmtest)
library(knitr)         # Function `kable()` to convert data frames into tables for reports.
#knitr::opts_knit$set(root.dir='..')

library(kableExtra)        # Enhancing kable() possibilities
library(DT)            # Interactive tables for HTML documents (DataTables).
library(fmckage)
library(janitor)

library(ProjectTemplate)
setwd("..")
load.project()
```

```{r options, echo = F}
# Chunk options
knitr::opts_chunk$set(
  echo       = TRUE,    # Should blocks with program code be shown in knitted documents?
  eval       = TRUE,    # Should program code be evaluated?
  fig.height = 6,       # Default height for plots.
  fig.width  = 10,       # Default width for plots.
  fig.align  = "center", # Default alignment for plots in knitted documents.
  warning = F
)

# Options to format numbers
options(        # For more detais see ?options
  scipen = 8,   # Show at least 8 digits in numbers before converting to exponential notation.
    digits = 4,   # Number of significant digits to print numbers.
    OutDec = ".", # Default decimal separator to print numbers.
    knitr.kable.NA = NA # Replacement for NA values in knitr::kable()
)

# Set ggplot options
new = theme_minimal()+
    theme(  # You can choose a pre-defined theme or customize it further
    text = element_text(family = "Arial", color = "black", size = 12),
    axis.title = element_text(face = "bold"),
    title = element_text(face = "bold"))
theme_set(new)
```

```{r contexte, echo = F, include = F}
#   Technique de cette chirurgie : prendre de l’os de la crête iliaque et le greffer au niveau de l’os alvéolaire du
#   maxillaire, pour reconstruire l’os de la mâchoire supérieure dans les fentes labio palatines

#   Les buts de cette chirurgie : 
#   -améliorer l’aspect esthétique
#   -permettre aux dents de se placer sur l’arcade (en gros)
#   -fermer la fistule buco-nasale 

# 151 patients inclus, correspondant à 162 GPP (GINGIVOPÉRIOSTOPLASTIE) (car 11 patients ont 2 fentes = f. bilaterales)

```

# Epidemio {.tabset}

## Sexe

```{r sexe}
table_prop(epi$sexe) %>% 
  kable(caption = "Sexe", col.names = c("sexe","n","%")) %>% 
  kable_paper()
```

## Fentes

```{r fentes}
rbind(table_prop(epi$complete),
      table_prop(epi$bilaterale),
      table_prop(epi$cote)) %>%
  kable(col.names = c("Fentes","n","prop"), caption = "Fentes") %>%
  kable_paper() %>% 
  pack_rows(start_row = 1,end_row = 2,"Complète") %>% 
  pack_rows(start_row = 3,end_row = 4,"Bilatérale") %>% 
  pack_rows(start_row = 5,end_row = 8,"Coté")


table(epi$complete,epi$bilaterale,epi$cote, deparse.level = 2, useNA = "ifany") %>% 
  data.frame() %>%
  mutate("%"=Freq*100/sum(Freq)) %>%
  filter(Freq!=0) %>%
  kable(caption = "Fentes cross-table") %>%
  kable_paper(lightable_options = "striped", ) %>% 
  add_footnote(c("Complète 1/0 = oui/non",
                 "Bilatérale 1/0 = oui/non",
                 "NA = not available"))
```

## Fentes by sexe

```{r fentes by sexe, echo=F}
table(epi$sexe,epi$bilaterale,epi$complete, deparse.level = 2, useNA = "ifany") %>% 
  data.frame() %>%
  group_by(epi.sexe) %>% 
  mutate("%"=Freq*100/sum(Freq)) %>%
  filter(Freq!=0) %>% 
  arrange(epi.sexe) %>% 
  ungroup() %>% 
  select(-epi.sexe) %>% 
  kable(caption = "Fentes by sexe") %>%
  kable_paper(lightable_options = "striped") %>% 
  pack_rows(start_row = 1,end_row = 4,"Femmes") %>% 
  pack_rows(start_row = 5,end_row = 8,"Hommes") %>%
  add_footnote(c("Complète 1/0 = oui/non",
                 "Bilatérale 1/0 = oui/non",
                 "NA = not available"))
```

# Etude {.tabset}
## Fentes operées
```{r fentes_operées}
table(etude$bilaterale,etude$cote_opere) %>%
    as.data.frame() %>%
    mutate("%"=Freq*100/sum(Freq,na.rm=T)) %>%
    adorn_totals() %>% 
    kable(col.names = c("Fente","Coté operé","n","%")) %>% 
    kable_paper(lightable_options = "striped")
```

## Prelevement iliaque
```{r prelevement iliaque}
table(etude$prelevement_iliaque) %>% 
    as.data.frame() %>%
    mutate("%"=Freq*100/sum(Freq,na.rm=T)) %>% 
    adorn_totals() %>% 
    kable(col.names = c("Prelevement iliaque","n","%")) %>% kable_paper()
```

## Age patients
```{r age patients}
# Create the age groups using cut
etude$age_group <- cut(as.numeric(etude$age/12), breaks = seq(0, 20, 1), include.lowest = TRUE)

    # Calculate the counts for each age group and sex
tab <- etude %>%
    count(age_group, sexe, name = "count")

    # Create the plot
ggplot(data = tab, aes(x = age_group, y = ifelse(sexe == "F", -count, count), fill = sexe)) +
    geom_bar(stat = "identity", position = "identity") +
    scale_y_continuous(labels = abs, breaks = seq(-20,20,1)) +
    labs(title = "Pyramid Age", x = "Age (années)", y = "n", fill = "Sexe") +
    theme_minimal() +
    coord_flip()

```

## Age intervention
```{r age intervention}
# Dispersion mesures
tab = describe(etude$age_intervention,fast = T) %>%
  round(2) %>% 
  as.data.frame %>%
  select(-1,-8) 

tab2 = tab %>% 
  mutate(across(mean:range, function(x) fmckage::convert_time(x,
                                                  from = "months", 
                                                  to = c("years","months","days"), 
                                                  warn_residual = F)))

# Binding the 2 tables together
rbind(tab,tab2) %>% `row.names<-`(c("Mois","Years - months - days")) %>% 
    kable(col.names = c("n", "moyenne", "écart type","min","max","range"), 
          row.names = T,
          caption = "Age intervention - Mesures de dispersion", 
          digits = 2) %>% 
    kable_paper() 

# Dispersion mesures by sexe
tab = etude %>% 
  group_by(sexe) %>% 
  summarise(age_intervention = describe(age_intervention,fast = T)) %>% 
  unnest(cols = c(age_intervention)) %>% 
  mutate(across(mean:range, function(x) round(x, 2)))

tab2 = tab %>% 
  mutate(across(mean:se ,function(x) convert_time(x,from = "months", to = c("years","months","days")))) 

rbind(tab, tab2) %>%  
    select(-vars,-se) %>%   
    kable(col.names = c("sexe","n", "moyenne", "écart type","min","max","range"), 
          row.names = F,
          caption = "Age intervention - Mesures de dispersion by sexe") %>% 
    kable_paper() %>% 
  pack_rows("Mois",1,2) %>% 
  pack_rows("Years - months - days",3,4)


```

## Traitement ODF
```{r ttt odf}
# 1) Combien de patients ont eu un traitement ODF pré chir ?
etude %>% 
  distinct(patid, odf_prechir) %$%
  table_prop(odf_prechir)  %>% 
  kable(col.names = c("ODF prechir","n","%")) %>% 
  kable_paper() %>%
  add_footnote(c("ODF prechir 1/0 = oui/non",
                 "NA = not available"))


# 2) temps moyen d’une prise en charge ODF avant la chirurgie 
tab = describe(etude$odf_prechir_months, fast = T) %>% round(2) %>% 
  select(-1,-8) %>% 
  as.data.frame() 

tab2 = etude %>%
  group_by(sexe) %>%
  summarise(odf_prechir_months = describe(odf_prechir_months, fast = T)) %>% 
  unnest(cols = odf_prechir_months) %>% 
  mutate(across(mean:range, round, 2)) %>% 
  select(-2,-9) %>%
  column_to_rownames("sexe")
  
tab3 = rbind(tab,tab2) %>% 
  mutate(across(mean:range, function(x) convert_time(x, from = "months", to = c("years","months","days"))))


    # joining tables
rbind(tab,tab2,tab3) %>% 
  `row.names<-`(c("Tous","F","M","tous","f","m")) %>% 
    kable(col.names = c("n", "moyenne", "écart type","min","max","range"), 
          row.names = T,
          caption = "Durée prise en charge ODF pre chir - Mesures de dispersion", 
          digits = 2) %>% 
  kable_paper() %>% 
  pack_rows("Mois",1,3) %>% 
  pack_rows("Years - months - days",4,6)

```

## Temps hospitalisation
```{r duree hospit}
# Mesures de dispersion
t_hospit = describe(etude$duree_sej, fast = T)[-c(1,8)] %>% round(2)

tab1 = t_hospit %>% 
    tibble %>% 
    mutate(across(mean:range, function(x) convert_time(x, from="days", to = c("days","hours"))))

tab2 = t_hospit %>%
    tibble %>% 
    mutate(across(mean:range, function(x) convert_time(x, from="days", to = c("hours","minutes"))))

    # Binding
rbind(as.character(t_hospit),tab1,tab2) %>%  
    mutate(rownames = c("","Days","Hours")) %>% 
    column_to_rownames(var = "rownames") %>% 
    kable(row.names = T, 
          caption = "Temps d'hispitalisation - mesures de dispersion", 
          col.names = c("n", "moyenne", "écart type","min","max","range")) %>%
    kable_paper()

# Table durée hospitalisation
table_prop(etude$duree_sej, name = "Durée hospit (jours)") %>% 
    kable(caption = "Tableau durée sejour") %>%
    kable_paper()

```

## Suites
```{r suites}
table_prop(etude$complications, name = "complications") %>% 
    kable(caption = "Suites compliquées oui/non") %>% 
    kable_paper()
```

# Learning curve
```{r learning curve, message=F}
ggplot(lc, aes(x = as_date(date), y = time, color = factor(interne, labels = c("Oui","Non"))))+
    geom_point(position = "identity")+
    scale_y_continuous(breaks = seq(0,300,20))+
    scale_x_date(labels = as.character(seq(2010,2024,1)), date_breaks = "1 year")+
    geom_smooth(method="loess", span = 0.75)+
    labs(title = "Evolution temps d'intervention",
         y = "Temps (minutes)",
         x = "Date intervention",
         color = "Interne")

```

40 à 60min plus rapide AVEC interne

```{r linear regression, include = F}
# Trying a lm()
model <- lm(time ~ date, data = lc)
summary(model)

# Testing the assumption of linear model
    # Residuals vs Fitted values plot
plot(model, which = 1)
    # Q-Q plot
qqnorm(residuals(model))
qqline(residuals(model))
    # Shapiro-Wilk test
shapiro.test(residuals(model))
    # Durbin Watson Test
dwtest(model)

# Both the Shapiro-Wilk test for normality and the Durbin-Watson test for independence suggest violations of the assumptions of the linear regression model.
# 
# Normality assumption: The Shapiro-Wilk test p-value is very small, which provides evidence against the hypothesis that your residuals are normally distributed. It implies that the distribution of your residuals deviates from a normal distribution.
# 
# Independence assumption: The Durbin-Watson test p-value is less than 0.05, indicating that there is a statistically significant autocorrelation in the residuals, which means the independence assumption is violated.

```




