---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r load}
library(tidyverse)
library(fmckage)
library(stringr)
library(magrittr)
library(ProjectTemplate)
library(lubridate)
load.project()

```

```{r}
surgery = pat_operes %>% 
    select(patid,evtid,datent) %>% 
    distinct() %>% 
    rename(date_surgery = datent) %>% 
    group_by(patid,evtid) %>% 
    summarise(date_surgery = min(date_surgery), .groups = "keep")

surgery = surgery %>% rename(chir_id = evtid)
reprise = reprise %>% rename(infection_id = evtid)

data = full_join(surgery,reprise) %>%
    mutate(diff = date_reprise - date(date_surgery)) %>%
    #filter(diff > -5 & diff<400) %>% 
  arrange(patid,date_surgery) %>% left_join(pat_operes[c("patid","evtid","implant","infection")], by = c("patid", "chir_id" = "evtid")) %>% distinct
```

```{r}

# 652 pazienti operati al rachide
pat_operes %$% n_distinct(patid)

# UF frequentate
pat_operes$ufpro %>% table

pat_operes

# Time surgery e infezione
data %>% 
    ggplot()+
    geom_density(aes(date(date_surgery), after_stat(count)))+
    geom_density(aes(date(date_reprise), after_stat(count)), col = "red")+
    scale_x_date(date_breaks = "1 month")


pat_operes %>% select(evtid,dateacte) %>% distinct %>% 
    ggplot()+
    geom_histogram(aes(date(dateacte), after_stat(count)), color = "white", binwidth = 7)+ 
    scale_x_date(date_breaks = "1 month")

data %>% 
    ggplot()+
    geom_histogram(aes(date(date_surgery), after_stat(count)), color = "white", binwidth = 7)+ 
    scale_x_date(date_breaks = "1 month")

```

