---
title: "Thèse Sara S."
author: "Francesco MONTI"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: true
editor_options: 
  
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(magrittr)      # Operator %>% and additional pipe-friendly functions.
library(tidyverse)     # The main "tidyverse" packages.
library(openxlsx)
library(ggplot2)
library(DT)
library(conflicted)
library(knitr)
library(fmckage)

knitr::opts_chunk$set(
	  echo       = FALSE,    # Should blocks with program code be shown in knitted documents?
	  eval       = TRUE,    # Should program code be evaluated?
	  fig.height = 6,       # Default height for plots.
	  fig.width  = 10,       # Default width for plots.
	  fig.align  = "center" # Default alignment for plots in knitted documents.
        )

theme_set(theme_bw()) # Default ggplot2 theme


conflict_prefer("filter", "dplyr")
conflict_prefer("lag",    "dplyr")

data = read.xlsx("Tableau biostat.xlsx", sheet = 1) %>% 
        as_tibble() %>%
        select(id:commentaires)
```

```{r}
data = data %>% 
        mutate(across(where(is.character),function(x) str_squish(x)),
               across(everything(), function(x) ifelse(as.character(x)=="",NA,x)),
               across(everything(), function(x) ifelse(as.character(x)=="?",NA,x)),
               taille = as.numeric(str_replace(taille,",",".")),
               taille = case_when(taille < 10 ~ taille * 100,
                                  taille < 100 ~ taille + 100,
                                  TRUE ~ taille),
               imc = round(as.numeric(poids)/(as.numeric(taille)/100)^2,2)
               ) 

data = data %>% mutate(oh = ifelse(oh %in% c("Jamais","Non sevré","Sevré"),oh,NA))

data$ville_suivi[which(data$ville_suivi=="CHU LIlle")] = "CHU Lille"

```


# Exploration données
## Dimensions
`r nrow(data)` patients, `r ncol(data)` colonnes.

## Données manquantes
Pour certaines variables, valeur manquante = "absence" très probablement, pour d'autre c'est plus difficile à dire. Dans tous les cas, scientifiquement ce n'est pas une position idéale.

```{r tableau valeurs manquantes}

apply(data,2, function(x) sum(is.na(x))) %>%
        as.data.frame() %>%
        rownames_to_column() %>%
        `colnames<-`(c("variable","valeurs_manquantes")) %>% 
        mutate(pourcentage = round(valeurs_manquantes*100 / nrow(data),2)) %>% 
        datatable(caption = htmltools::tags$caption(
                            style = 'caption-side: top; text-align: left; 
                                     font-size: 18px; font-weight: bold; 
                                     padding: 10px;',
                            'Valeurs manquantes par variable'
  ),
                  options = list(
                         pageLength = 10,
                         scrollX = TRUE,
                         scrollX = T,
                         width = "auto"
                         )
        )
```

```{r}
# need to fix chu labels

data %>%
  group_by(ville_suivi) %>%
  summarise(
    across(everything(), ~sum(is.na(.))),
    nb_patients = n()
  ) %>% 
  rowwise() %>%
  mutate(
    na_count = sum(c_across(where(is.numeric))),
    na_count_per_row = na_count / nb_patients
  ) %>%
  relocate(na_count, .after = ville_suivi) %>%
  relocate(nb_patients, .after = ville_suivi) %>%
  relocate(na_count_per_row, .after = na_count) %>%
  arrange(desc(na_count_per_row)) %>% 
  mutate(#na_pourcentage = na_count*100/(nb_patients*(ncol(.)-2)),
               na_pourcentage = na_count*100/(nb_patients*(ncol(data)-2)),
               across(where(is.numeric), function(x) round(x,2))
               ) %>% 
  relocate(na_pourcentage, .after = na_count_per_row) %>% 
  datatable(caption = htmltools::tags$caption(
                            style = 'caption-side: top; text-align: left; 
                                     font-size: 18px; font-weight: bold; 
                                     padding: 10px;',
                            'Valeurs manquantes par variable et ville'
                        ),
                  options = list(
                         pageLength = 10,
                         scrollX = TRUE,
                         scrollX = T,
                         width = "auto"
                         )
                )
        
```


## Sexe & age
```{r sexe et age}
data %>% ffreq("sexe") %>% kable(caption = "Sexe")

fmckage::fdescribe(data,"age","sexe") %>% kable(caption = "Age by sexe")
```

## Age diag VHD
```{r}
data %>%
        group_by(sexe) %>%
        summarise(mean = 
                        mean(age_diag_vhd, na.rm = TRUE),
                    sd = sd(age_diag_vhd, na.rm = TRUE),
                    min = min(age_diag_vhd, na.rm = TRUE),
                    max = max(age_diag_vhd, na.rm = TRUE),
                    range = max(age_diag_vhd, na.rm = TRUE) - min(age_diag_vhd, na.rm = TRUE),
                    se = sd(age_diag_vhd, na.rm = TRUE) / sqrt(n())) %>% 
        kable(caption = "Age au diag VHD by sexe")
```

## OH
```{r}
data %>% 
        count(oh,sexe) %>% 
        group_by(sexe) %>%
        mutate(pourcentage_by_sexe = round(n*100/sum(n),2)) %>%
        arrange(sexe) %>% 
        ungroup() %>%
        mutate(pourcentage_global = round(n*100/sum(n),2)) %>% 
        datatable(caption = htmltools::tags$caption(
                            style = 'caption-side: top; text-align: left; 
                                     font-size: 18px; font-weight: bold; 
                                     padding: 10px;',
                            "Consommation OH by sexe"),
                  options = list(
                pageLength = 10,
                scrollX = TRUE,
                width = "auto",
                scrollX = T)
                )
```

